/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const MangaEntryInput = IDL.Record({
  'status' : IDL.Variant({ 'Complete' : IDL.Null, 'Incomplete' : IDL.Null }),
  'coverImageKey' : IDL.Opt(IDL.Text),
  'chaptersOwned' : IDL.Float64,
  'mainTitle' : IDL.Text,
  'artRating' : IDL.Float64,
  'altTitle' : IDL.Text,
  'chaptersRead' : IDL.Float64,
  'cenLevel' : IDL.Float64,
  'synopsis' : IDL.Text,
  'genres' : IDL.Vec(IDL.Text),
  'notes' : IDL.Text,
  'rating' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const MangaEntry = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({ 'Complete' : IDL.Null, 'Incomplete' : IDL.Null }),
  'coverImageKey' : IDL.Opt(IDL.Text),
  'chaptersOwned' : IDL.Float64,
  'mainTitle' : IDL.Text,
  'artRating' : IDL.Float64,
  'altTitle' : IDL.Text,
  'chaptersRead' : IDL.Float64,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
  'cenLevel' : IDL.Float64,
  'synopsis' : IDL.Text,
  'genres' : IDL.Vec(IDL.Text),
  'notes' : IDL.Text,
  'rating' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addEntry' : IDL.Func([MangaEntryInput], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteEntry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEntries' : IDL.Func([], [IDL.Vec(MangaEntry)], ['query']),
  'getEntry' : IDL.Func([IDL.Nat], [IDL.Opt(MangaEntry)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isUnlocked' : IDL.Func([], [IDL.Bool], ['query']),
  'resetAttempts' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateEntry' : IDL.Func([IDL.Nat, MangaEntryInput], [IDL.Bool], []),
  'verifyPassword' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'fail' : IDL.Nat, 'locked' : IDL.Int })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const MangaEntryInput = IDL.Record({
    'status' : IDL.Variant({ 'Complete' : IDL.Null, 'Incomplete' : IDL.Null }),
    'coverImageKey' : IDL.Opt(IDL.Text),
    'chaptersOwned' : IDL.Float64,
    'mainTitle' : IDL.Text,
    'artRating' : IDL.Float64,
    'altTitle' : IDL.Text,
    'chaptersRead' : IDL.Float64,
    'cenLevel' : IDL.Float64,
    'synopsis' : IDL.Text,
    'genres' : IDL.Vec(IDL.Text),
    'notes' : IDL.Text,
    'rating' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const MangaEntry = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({ 'Complete' : IDL.Null, 'Incomplete' : IDL.Null }),
    'coverImageKey' : IDL.Opt(IDL.Text),
    'chaptersOwned' : IDL.Float64,
    'mainTitle' : IDL.Text,
    'artRating' : IDL.Float64,
    'altTitle' : IDL.Text,
    'chaptersRead' : IDL.Float64,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'cenLevel' : IDL.Float64,
    'synopsis' : IDL.Text,
    'genres' : IDL.Vec(IDL.Text),
    'notes' : IDL.Text,
    'rating' : IDL.Float64,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addEntry' : IDL.Func([MangaEntryInput], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteEntry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEntries' : IDL.Func([], [IDL.Vec(MangaEntry)], ['query']),
    'getEntry' : IDL.Func([IDL.Nat], [IDL.Opt(MangaEntry)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isUnlocked' : IDL.Func([], [IDL.Bool], ['query']),
    'resetAttempts' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateEntry' : IDL.Func([IDL.Nat, MangaEntryInput], [IDL.Bool], []),
    'verifyPassword' : IDL.Func(
        [IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Null,
            'fail' : IDL.Nat,
            'locked' : IDL.Int,
          }),
        ],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };